# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: equipment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65quipment.proto\x12\x04grpc\"\x19\n\tEquipment\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t2C\n\tScheduler\x12\x36\n\x13ScheduleMaintenance\x12\x0f.grpc.Equipment\x1a\x0e.grpc.ResponseB\x17Z\x15\x61utoMaintenance/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'equipment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025autoMaintenance/proto'
  _EQUIPMENT._serialized_start=25
  _EQUIPMENT._serialized_end=50
  _RESPONSE._serialized_start=52
  _RESPONSE._serialized_end=78
  _SCHEDULER._serialized_start=80
  _SCHEDULER._serialized_end=147
# @@protoc_insertion_point(module_scope)
