version: "3.9"

services:
  sms:
    env_file:
        - ./sms/sms.env
    build:
      context: ./sms
      dockerfile: Dockerfile
    # depends_on:
    #   - rabbitmq
    restart: on-failure

  email:
    env_file:
      - ./email/email.env
    build:
      context: ./email
      dockerfile: Dockerfile
    # depends_on:
    #   - rabbitmq
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: esd-rabbit
    # networks:
    #   - kong-net
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq
