version: "3.9"

networks:
  test-net:
    driver: bridge


services:
  sms:
    env_file:
        - ./sms/sms.env
    build:
      context: ./sms
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
    # networks:
    #   - test-net
    container_name: sms

  email:
    env_file:
      - ./email/email.env
    build:
      context: ./email
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
    # networks:
    #   - test-net
    container_name: email

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: esd-rabbit
    # networks:
    #   - test-net
    ports:
      # - "5672:5672"
      - "15672:15672"
    # networks:
    #   - test-net
    container_name: rabbitmq
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq

  testsend:
    build:
      context: ./rmqTestSend
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
    ports:
      - "4000:4000"
    # networks:
    #   - test-net
    container_name: testSend

  login:
    build:
      context: ./login
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3001:3001"
    container_name: login
    env_file:
        - ./login/utils/login.env

  equipment:
    build:
      context: ./equipment
      dockerfile: Dockerfile
    restart: on-failure
    container_name: equipment
    